### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by attinderdhillon** [varnav/ExifDate2FS#2]
Breaks with the below error.

`Traceback (most recent call last):
  File "/usr/local/bin/exifdate2fs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/exifdate2fs/__init__.py", line 74, in main
    time_object = time.strptime(datetime_original, '%Y:%m:%d %H:%M:%S')
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2007:03:08 15:57: 7' does not match format '%Y:%m:%d %H:%M:%S'`

**Comment by varnav** [comment]
Looks like it meets some unexpected broken data in the EXIF, `2007:03:08 15:57: 7` instead of expected `2007:03:08 15:57:07`

Can you please give me the file it breaks at?

Thank you!

**Comment by varnav** [comment]
Fixed (hopefully) in latest main branch. https://github.com/varnav/ExifDate2FS/commit/714ada4d07b2e22f10cbd77d94cdf48d313f1d57
Can you give it a try?

`pip install -U --pre exifdate2fs`

**Comment by attinderdhillon** [comment]
It didn't fix the issue, Out of 100k images only couple of images have the issue. So it is not a big issue as I sort it manually.
I am emailing you the image if you'd like to take a look.

Thank you

`
Processing recursively starting from /home/timg
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exifdate2fs/__init__.py", line 152, in main
    time_object = time.strptime(datetime_original, '%Y:%m:%d %H:%M:%S')
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2007:03:08 15:46: 5' does not match format '%Y:%m:%d %H:%M:%S'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/exifdate2fs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/exifdate2fs/__init__.py", line 159, in main
    log.error(str(filepath), '%s EXIF DateTimeOriginal is corrupt')
Message: '/home/timg/aaja06.jpg'
Arguments: ('%s EXIF DateTimeOriginal is corrupt',)
0 files processed 1 skipped in 0.03591346740722656
root@D-Server:/home# exifdate2fs --version
exifdate2fs 0.8.10.dev1
`

**Comment by varnav** [comment]
Ah I hate this python-2-ism.
Ok now fixed for real in prerelease, I'll make it a release soon.

Thanks!
